### ISSUE TITLE
Request for README and Documentation

### ISSUE THREAD

**Issue by Ad7amstein** [ShehabDiab0/Al-Mutabie-Discord-Bot#19]
Hi @ShehabDiab0,

I'm interested in learning more about the Al-Mutabie-Discord-Bot project. To better understand what the project is about, could you please add a README file that includes:
- A brief overview of the project.
- Installation instructions.
- Usage examples.
- Contribution guidelines (If contributions are currently welcomed).

Additionally, any documentation on the project's architecture and key components.

Thank you for your time and assistance!

**Comment by ShehabDiab0** [comment]
Thank you for opening this issue, and I appreciate your interest
will close this issue as soon as I finish writing the README file.

**Comment by ShehabDiab0** [comment]
Done writing README with contribution guideline,
If you have other problems or questions, please consider opening another issue or contacting us directly (you will find our contacts in README).
Thank you for opening this issue.
